# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [48]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [49]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [50]:
print(np.__version__,np.show_config)

1.19.5 <function show at 0x000002FA4FFF0700>


#### 3. Create a null vector of size 10 (★☆☆)

In [51]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [52]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.itemsize*Z.size))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [53]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [54]:
Z = np.zeros(10)
Z[5] = 1
print(Z)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [55]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [56]:
Z = np.flip(Z)
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [57]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [58]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [59]:
Z = np.identity(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [60]:
Z = np.random.random((3,3,3))
Z

array([[[0.69394407, 0.92540201, 0.53196125],
        [0.44415885, 0.06025785, 0.89935027],
        [0.0020726 , 0.76426527, 0.40037171]],

       [[0.70338527, 0.24975023, 0.85931292],
        [0.25758958, 0.64642043, 0.85233565],
        [0.7682857 , 0.71298252, 0.36075598]],

       [[0.844222  , 0.83035367, 0.64762135],
        [0.76172774, 0.74467791, 0.48234535],
        [0.42234065, 0.59985284, 0.54153971]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [61]:
Z = np.random.random((10,10))
print(Z)
print(np.min(Z))
print(np.max(Z))


[[0.8221975  0.84243677 0.26615499 0.05607249 0.61258802 0.59106458
  0.88471323 0.81831635 0.58571877 0.43647156]
 [0.77380972 0.76085115 0.99307138 0.1364515  0.13959988 0.39239304
  0.97442119 0.23673095 0.95046282 0.91993865]
 [0.90757756 0.28410547 0.63556891 0.08681327 0.14169906 0.93866355
  0.03510463 0.22459538 0.31978382 0.35174615]
 [0.95120794 0.94695661 0.50859531 0.96804919 0.15723579 0.83629585
  0.86773577 0.50556154 0.56284335 0.70199034]
 [0.18328125 0.07913862 0.38422687 0.10067124 0.56512486 0.28681772
  0.37564667 0.86676047 0.65422214 0.51616084]
 [0.89211404 0.87036949 0.60249423 0.7859051  0.24730624 0.54290973
  0.88106118 0.36191562 0.58568978 0.21091904]
 [0.11573854 0.73718185 0.89722    0.81189916 0.47997722 0.06383184
  0.84016517 0.05319524 0.05786241 0.44038564]
 [0.06465206 0.88390485 0.24838379 0.43422761 0.11142962 0.81532024
  0.06258889 0.83397565 0.35572601 0.53354434]
 [0.08805503 0.06990728 0.87399053 0.21528629 0.06181296 0.96317482
  0.00609931

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [62]:
Z = np.random.random(30)
print(np.mean(Z))

0.42915160524434987


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [63]:
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [64]:
print(np.pad(Z,pad_width=1,mode='constant',constant_values=0))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [65]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [66]:
Z = np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [67]:
Z = np.zeros((8,8))
Z[1::2,::2]=1
Z[::2,1::2]=1
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [68]:
a = np.unravel_index(99,(6,7,8))
a

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [69]:
Y = np.tile(np.eye(2),(4,4))
Y


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [70]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
Z

array([[ 1.08685145, -1.27251468, -1.27132339, -1.33285397,  0.84943731],
       [ 0.10247527,  1.28942617,  1.32989754, -0.06517585,  1.48401656],
       [-1.06717706, -0.60304009, -0.8531753 , -0.96408151, -0.24439262],
       [-0.71889975,  0.99916921, -1.14306208, -0.23817399,  1.59248396],
       [-0.270466  , -1.04230145,  1.40310897,  0.80915232,  0.14061898]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [71]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [72]:
print(np.dot(np.ones((5,3)),np.ones((3,2))))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [73]:
Z = np.random.randint(1,12,20)
print(Z)
Z[(3<Z)&(Z<8)]*=-1
print(Z)

[ 2  1  6  3  8  9  9  4  7  4  8  4  8  3  2  6 10  4  4  4]
[ 2  1 -6  3  8  9  9 -4 -7 -4  8 -4  8  3  2 -6 10 -4 -4 -4]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [74]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [75]:
Z=np.random.randint(5,8)
print(Z**Z,2 << Z >> 2,Z <- Z,1j*Z,Z/1/1,Z<Z>Z)

46656 32 False 6j 6.0 False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [76]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-76-6caa14b62dca>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0)/np.array(0))
<ipython-input-76-6caa14b62dca>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [77]:
Z = np.random.uniform(-10,10,10)
print(Z)
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


[-5.5577278  -9.55360648 -9.31389217 -8.94842043  5.58601036 -4.35003468
 -6.38666598 -9.87551706 -7.35587315 -2.05590425]
[ -6. -10. -10.  -9.   6.  -5.  -7. -10.  -8.  -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [78]:
Z = np.random.randint(-10,10,(5,5))
Y = np.random.randint(-10,10,(5,5))
print(Z, "\n\n", Y, "\n\n", np.intersect1d(Z,Y))

[[  6  -8  -1  -8   4]
 [  3   0  -1  -6  -4]
 [ -9   1   8  -5  -1]
 [  2  -7 -10   2   5]
 [ -8   1  -5   4  -1]] 

 [[  2  -9  -3  -6   0]
 [ -4 -10   7  -9  -6]
 [ -5   8   6  -8   6]
 [ -3  -6   9  -4   1]
 [ -1   3  -1   6  -1]] 

 [-10  -9  -8  -6  -5  -4  -1   0   1   2   3   6   8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [79]:
# # Suicide mode on
# defaults = np.seterr(all="ignore")
# Z = np.ones(1) / 0

# # Back to sanity
# _ = np.seterr(**defaults)

# # Equivalently with a context manager
# with np.errstate(all="ignore"):
#     np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [80]:
print(np.emath.sqrt(-1)==np.sqrt(-1))

False


<ipython-input-80-044b0f8630f7>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.emath.sqrt(-1)==np.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [81]:
yesterday = np.datetime64('today') - timedelta64(1)
today = np.datetime64('today') 
tommorow = np.datetime64('today') + timedelta64(1)
print("Yesterday:-",yesterday,"\nToday",today,"\nTommorow",tommorow)


Yesterday:- 2022-05-31 
Today 2022-06-01 
Tommorow 2022-06-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [82]:
Z = np.arange('2016-07','2016-08',dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [83]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [84]:
Z = np.random.uniform(0,10,10)
Z
print(Z-Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z//1)

[8. 2. 0. 4. 6. 0. 6. 1. 0. 2.]
[8. 2. 0. 4. 6. 0. 6. 1. 0. 2.]
[8. 2. 0. 4. 6. 0. 6. 1. 0. 2.]
[8. 2. 0. 4. 6. 0. 6. 1. 0. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [85]:
Z = np.tile(np.arange(0, 5),(5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [86]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [87]:
Z = np.linspace(0,5,11,endpoint='False')[1:]
Z

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [88]:
Z = np.random.randint(0,10,10)
Z=np.sort(Z)
Z

array([0, 1, 2, 3, 4, 4, 5, 5, 5, 7])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [89]:
Z=np.add.reduce(Z)
Z

36

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [90]:
A = np.random.randint(0,2,3)
B = np.random.randint(0,2,3)
print(A,B)

equal = np.array_equal(A,B)
print(equal)


[0 1 1] [1 1 0]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [91]:
A.flags.writeable= False
# A[0]=5
A

array([0, 1, 1])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [92]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.16359972 0.93450252 0.86504286 0.65655394 0.19093611 0.64418471
 1.10823523 0.33380547 0.29082182 1.09900208]
[0.78579331 0.45208485 0.7531822  1.24283008 1.22334998 0.20234213
 1.07216031 0.01522095 1.16776761 0.88669472]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [93]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()]=0
print(Z)

[0.72734691 0.17227741 0.62662764 0.22630351 0.94405572 0.89207817
 0.86217624 0.71692345 0.7869678  0.62714903]
[0.72734691 0.17227741 0.62662764 0.22630351 0.         0.89207817
 0.86217624 0.71692345 0.7869678  0.62714903]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)